[build]
  publish = "public"
  command = "hugo -d public"

[build.environment]
  HUGO_VERSION = "{{hugo_version}}"
  HUGO_BUILDFUTURE = "true"

[context.deploy-preview.environment]
  command = "hugo --baseURL $DEPLOY_PRIME_URL"
